apiVersion: v1
kind: Service
metadata:
  name: svc-site-php
  labels:
    app: site-php
    tier: backend
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
  selector:
    app: site-php
    tier: backend
